server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      #defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-order-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
        probability: 1
